
version: "3.1"

services:
  apiBank-db:
    container_name: apiBank-db
    image: postgres:13.2-alpine
    environment:
      POSTGRES_DB: apiBank-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:

apiBank_idempotency:
    image: "redis:6-alpine"
    command: redis-server
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
      interval: 5s
      timeout: 5s
      retries: 5